### ISSUE TITLE
GIthub should have thanks feature

### ISSUE THREAD

**Issue by DaveM2011** [symisc/PH7#14]
Dude this PH7 is amazing, the memory use is extremely low less than 500bytes serving several forms and with several functions added + loading/saving session data that i have yet to complete. But so far within about 4 days i have added ( with kids annoying me ;) )

`{"header", ph7_header},
{"setcookie", ph7_setcookie},
{"memory_get_usage", ph7_memory_get_usage},
{"move_uploaded_file", ph7_move_uploaded_file}`

along with $_SESSION and $_FILES support but like i said session not complete yet but so far so good and the fact that its all embedded into a single binary is just simply amazing.  Im not sure you will fully get what i mean so if not ill just say Well done

**Comment by symisc** [comment]
Ah Great Dave, Could you share the foreign functions you've implemented for PH7?

**Comment by DaveM2011** [comment]
There not very clean atm but sure there based on the libh2o, multipart_parser, and libsdb from github give me a few days maybe a week to clean up the code and finish session at least converting objects and array to strings and ill gladly share

**Comment by symisc** [comment]
All right!

**Comment by DaveM2011** [comment]
Ohhh i got memory wrong its kb not bytes but still pretty good here is one of my extras so far [Gist](https://gist.github.com/DaveM2011/84f0555c39bd17b19539b1c11739287e) there about the only ones that do not require an extra library my memory avg is between 500kb and 700kb do u think this is good?

**Comment by DaveM2011** [comment]
I lie i dont fully know what the mem use is after reading lots i figured out it was inaccurate :(

**Comment by DaveM2011** [comment]
Ohh man i just made a dl function just to read [ph7_create_function]This function must be called before program execution via ph7_vm_exec().

**Comment by DaveM2011** [comment]
erm if i could find it i could it was 2yrs ago but i could recreate most things easily

**Comment by DaveM2011** [comment]
ill look around pc see if i can spot my work

**Comment by morpheouss** [comment]
@DaveM2011 great, waiting for news :)

**Comment by DaveM2011** [comment]
this is proberly most of it but i gave up the project long ago as its more fun rather than work https://gist.github.com/DaveM2011/5b3d36c858ad8702a1696727d0943bbd

**Comment by DaveM2011** [comment]
i have failed to find the one relating to session_start etc i will keep looking

**Comment by morpheouss** [comment]
thanks a lot, can i contact you somehow? no pm here

**Comment by DaveM2011** [comment]
sure erm telegram or gmail?

**Comment by morpheouss** [comment]
can be gmail?

**Comment by DaveM2011** [comment]
davem.2011@gmail.com

**Comment by DaveM2011** [comment]
are you subscribed to this thread?
