### ISSUE TITLE
PH7 into Embedded Web Server (missing examples)

### ISSUE THREAD

**Issue by sanyaade-iot** [symisc/PH7#21]
Hello Everybody,

I am porting PH7 to ESP8266 and other MCU. I am lloking for the examples:- ph7_http and ph7_webserver the link to them from the PH7 online/manual are dead links. So please help!

I have managed to compile PH7 with ESP8266 SDK (based on ph7_cgi.c) but I am hitting a deadlock getting it to work after flashing it into the micro-controller. I think seeing those examples will help. Many thanks!

I have already sent a request email from my gmail account to devel@symisc.net  and also through the forum and to chm 

Please help!

God blesses!!!

Best regards,
Sanyaade

**Comment by symisc** [comment]
Hi,

Check the [g-wan ](https://github.com/retailify/docker-gwan)project if you want to serve dynamic PH7 contents or simply build your own CGI HTTP fork() based server. A lot of samples are available to consult here on Github.
https://github.com/retailify/docker-gwan/blob/master/7.12.6/gwan/0.0.0.0:80/%230.0.0.0/old.csp/hello.ph7

**Comment by sanyaade-iot** [comment]
@symisc :

Many thanks for your quick response, very much appreciated. 
I will check those links now. I will update you and may ask for help.

Once again, many thanks for your support! :+1: 

God blesses!!!

Best regards,
Sanyaade

**Comment by sanyaade-iot** [comment]
@symisc : 

Bad news - I just look at Gwan again folowing those links and my own previous ones, Gwan is closed source still. 

This is not good since I am porting to hardware devices. I already achieve a working integration of PH7 with Mongoose and Civetweb on Ubuntu 16.04 desktop. 

The issue is that when I compiled for ESP8266 and ARM Cortext F4 while the applications run, ph7 was not parsing php scripts file.

Is there any alternative with PH7? Many thanks!

God blesses!!!

Best regards,
Sanyaade
