### ISSUE TITLE
Namespaces support

### ISSUE THREAD

**Issue by morpheouss** [symisc/PH7#22]
On your website, you stated that you have an early prototype of PH7 with namespace support, but you have decided to drop its implementation from the build. I would like to ask if you could share the version with namespace support available?

If you do not want to publish it to the public, please let me know via PM where can I find the version with namespaces.

Thank you!

**Comment by symisc** [comment]
You can request access to the PH7 source tree by emailing devel@symisc.net and specify the reason for that.

**Comment by symisc** [comment]
You should receive a response in the next few days.

**Comment by morpheouss** [comment]
Stil waiting

- Michal

**Comment by symisc** [comment]
Unfortunately the namespace extension is already deployed for a commercial customer that we cannot open to anyone due to some legal NDA

**Comment by morpheouss** [comment]
This suck
