### ISSUE TITLE
How to create a class with methods?

### ISSUE THREAD

**Issue by IngwiePhoenix** [symisc/PH7#33]
Hey, remember me? Been quite a while.

I have started to work with V and I am looking to build a tool that needs a scripting language - and that is how i randomly found ph7 again. Now, I would love to know if there is a way to create classes and methods? From what I remember, namespaces were never really implemented... So I am not even gonna ask how to add methods to namespaces just yet :)

Kind regards,
Ingwie

**Comment by symisc** [comment]
Creating classes and methods from your C code is not implemented in PH7. Only standard functions via [FFI ](https://ph7.symisc.net/func_intro.html) can be registered from the outside environment. A simple workaround, is to create the classes and methods in PHP and call the C functions from these methods.
