### ISSUE TITLE
non-amalgam code should be available

### ISSUE THREAD

**Issue by tboronczyk** [symisc/PH7#6]
The source code in its entirety should be available to encourage forks and community development; it is difficult to work with a single giant code file.

**Comment by tboronczyk** [comment]
Any update as to when the source in its entirity (separate files) will be available? "Soon" was 10 months ago. Just curious as I would really like to persuse the project's code

**Comment by symisc** [comment]
@tboronczyk Sorry for the delay, all the core developers are heavily focused now on other projects, but, still I'll make my best to upload the entire repo here this weekend. Meanwhile, you can request a PH7 snapshot by sending a mail to devel@symisc.net

**Comment by CurlyMoo** [comment]
Bump

**Comment by Dingo64** [comment]
@tboronczyk Did up succeed in compiling the amalgam code? I can't make it work. I can give you non-amalgam code if you could help me compile the code.

**Comment by JayFoxRox** [comment]
Bump, I feel like the repository should contain the raw source-tree, and CI or the Makefile should be responsible for concatenating all files (if the people actually need this).

Could also just have a ph7.c which does:

```c
#include "ph7_arrays.c"
#include "ph7_strings.c"
#include "ph7_files.c"
[...]
```

As-is, it's very hard to work with the codebase for anyone who wants to extend it.

**Comment by belliash** [comment]
They are not going to do anything with it.
You can de-amalgamate it on your own or find it over the net.
